# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='jobposition',
        ),
        migrations.AddField(
            model_name='employee',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
    ]
