# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_auto_20170413_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='jobposition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='workers.JobPosition'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='name',
            field=models.CharField(default='Programmer', max_length=200),
        ),
    ]
