# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_auto_20170414_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='jobposition',
            new_name='position',
        ),
    ]
